---
- name: Start Petstore PostgreSQL Pod
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Scale up Deployment to zero replicas
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: postgresql
        namespace: petstore
        definition:
          spec:
            replicas: 1

      register: scale_up_result

    - name: Display result
      debug:
        var: scale_up_result
