apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucketnames: minio
  endpoint: http://minio.minio.svc.cluster.local:9000
  region: us-east-1