apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
#  hashRing:
#    type: memberlist
#  limits:
#    global:
#      queries:
#        queryTimeout: 3m
  managementState: Managed
  size: 1x.small
  storage:
    schemas:
#      - effectiveDate: '2020-10-11'
      - effectiveDate: '2022-06-01'
        version: v13
    secret:
      name: logging-loki-s3
      type: s3
  storageClassName: gp3-csi # ここを修正
  tenants:
    mode: openshift-logging
